export const KEYS = {
  connects: "connects",
  devices: "devices",
  tags: "tags",
  company: "company",
  getMe: "getMe",
  users: "users",
  archive: "archive",
  statusMonitoring: "statusMonitoring",
  systemOverview: "systemOverview",
  overviewStations: "overviewStations",
  screens: "screens",
  health: "health",
  ready: "ready",
  tagValues: "tagValues",
  tagValuesLatest: "tagValuesLatest",
  tagValuesAggregates: "tagValuesAggregates",
  tagValuesStatistics: "tagValuesStatistics",
};
