export const KEYS = {
  connects: "connects",
  company: "company",
  getMe: "getMe",
  users: "users",
  archive: "archive",
  MODBUSDevices: "MODBUSDevices",
  MODBUSRegisters: "MODBUSRegisters",
  MODBUSRegistersByDeviceId: "MODBUSRegistersByDeviceId",
  MODBUSRegister: "MODBUSRegister",
  MODBUSreadingsByRegisterId: "MODBUSreadingsByRegisterId",
  OPCServers: "OPCServers",
  statusMonitoring: "statusMonitoring",
  OPCNodes: "OPCNodes",
  statusMonitoringModbus: "statusMonitoringModbus",
  statusMonitoringOPCUA: "statusMonitoringOPCUA",
  OPCNodeChildren: "OPCNodeChildren",
  readingsByServerId: "readingsByServerId",
  readingsByNodeId: "readingsByNodeId",
};
