export const URLS = {
  register: "auth/signup",
  login: "auth/login",
  connects: "connects/",
  company: "company/",
  getMe: "me",
  users: "users",
  nodes: "nodes/",
  archive: "archive_data/",
  MODBUSDevices: "api/devices",
  MODBUSRegisters: "api/registers",
  MODBUSRegistersByDeviceId: "api/registers/device",
  MODBUSreadingsByRegisterId: "api/readings/register",
  OPCServers: "api/opc-servers",
  statusMonitoring: "api/v1/status",
};
