export const URLS = {
  login: "auth/login",
  connects: "connections",
  sites: "sites",
  devices: "devices",
  tags: "tags",
  company: "company/",
  getMe: "me",
  users: "users",
  archive: "archive_data/",
  statusMonitoring: "api/v1/status",
  systemOverview: "overview",
  overviewStations: "overview/stations",
  screens: "screens",
  health: "health",
  ready: "ready",
  tagValues: "tag-values",
  tagValuesLatest: "tag-values/latest",
  tagValuesAggregates: "tag-values/aggregates",
  tagValuesStatistics: "tag-values/statistics",
};
