export const URLS = {
  register: "auth/signup",
  login: "auth/login",
  connects: "connections",
  devices: "devices",
  tags: "tags",
  company: "company/",
  getMe: "me",
  users: "users",
  nodes: "nodes/",
  archive: "archive_data/",
  MODBUSDevices: "api/devices",
  MODBUSRegisters: "api/registers",
  MODBUSRegistersByDeviceId: "api/registers/device",
  MODBUSreadingsByRegisterId: "api/readings/register",
  syncDevices: "api/polling/sync",
  actionPolling: "/api/polling/devices/",
  statusMonitoringModbus: "api/polling/status",
  OPCServers: "api/opc-servers",
  statusMonitoring: "api/v1/status",
  OPCNodes: "api/opc-nodes",
  statusMonitoringOPCUA: "api/opcua/status",
  syncServers: "api/opcua/sync",
  OPCNodeChildren: "api/opcua/browse/children",
  readingsByServerId: "api/opc-readings/server/",
  readingsByNodeId: "api/opc-readings/node/",
};
